### ISSUE TITLE
Two different payment options for one membership level

### ISSUE THREAD

**Issue by merlinthecat** [strangerstudios/pmpro-pay-by-check#5]
Hello,

Out of the box I cant see this option but it is not an unusual request -
how to set two different payment options for one membership level
i.e. pay monthly or pay annually for one membership level (in my case "Gold")
currently it seems that you have to set up another membership level (ie then have Gold monthly as one and Gold annually as a second) - issue then is you wouldn't be able to protect content pages, as it would be an either/or choice regarding annual or monthly....

Thanks!

**Comment by cdgdigital** [comment]
I do have similar problem with "payment options" on a specific membership level (annuity):
- Option-1: 12 installments of $35, on PayPal;
- Option-2: Single payment of $350, on PayPal;
- Option-3: Single payment of $350, on BankTransfer/Check.

Using "pmpro_level_groups.php" also does not solve the problem, since:
(i) I have to create "multiple levels" anyway (there are no "options");
(ii) Outcome gets confused on which payment method should use.

**Comment by kimcoleman** [comment]
This is possible with the Payment Plans Add On: https://www.paidmembershipspro.com/add-ons/pmpro-payment-plans/
