### ISSUE TITLE
new orders are not created automatically if subscription is recurring, and NO email is send 

### ISSUE THREAD

**Issue by cremigerhonig** [strangerstudios/pmpro-pay-by-check#66]
pmpro / pay by check is not creating new orders on a pay by check subscription 
no email is sent

**Comment by ideadude** [comment]
see here: https://github.com/strangerstudios/pmpro-pay-by-check/issues/65#issuecomment-1027301368

Let me know what you find.

**Comment by cremigerhonig** [comment]
cron jobs were not there, 
missing:
pmpropbc_cancel_overdue_orders
pmpropbc_recurring_orders
pmpropbc_reminder_emails

after deactivating and reactivation the pay by check plugin they were created again... why did they not show up in the first place?

**Comment by andrewlimaza** [comment]
@cremigerhonig glad to hear you have made progress, it's difficult to assume why this went wrong in the first place without replicating it consistently from our end.

It could have been caused by something specific to your site. If you need any further help please do not hesitate to reach out to our support team via https://www.paidmembershipspro.com/support
